### ISSUE TITLE
Webapp support

### ISSUE THREAD

**Issue by sabakakado** [carvajalconsultants/apollo-link-offline#11]
Hey, can you add webapp support?
I see that you can use it only if you have async storage from react native and I think the same can be accomplished with local storage.
Is it something that can be accomplished?

**Comment by miguelocarvajal** [comment]
Hey!

Actually we already have it. You simply need to use an asynchronous wrapper around localStorate.

See here:

https://github.com/carvajalconsultants/apollo-link-offline/issues/2#issuecomment-482827673

**Comment by miguelocarvajal** [comment]
Did you try localforage as mentioned in the same thread?

We haven't really used this on the web.

Let us know the result!

**Comment by sabakakado** [comment]
i added
`const asyncLocalStorage = {
	setItem: function (key: string, value: string) {
		return Promise.resolve().then(function () {
			localStorage.setItem(key, value);
		});
	},
	getItem: function (key: string) {
		return Promise.resolve().then(function () {
			return localStorage.getItem(key);
		});
	},
	removeItem: function (key: string) {
		return Promise.resolve().then(function () {
			return localStorage.removeItem(key);
		});
	},
};
`

and
`persistCache({
			cache,
			storage: asyncLocalStorage as PersistentStorage<
				PersistedData<NormalizedCacheObject>
			>,
			maxSize: false,
			debug: false,
		}).then(() => {
			setClient(client);
		});
`

now it saves in the localStorage but for some reason not while offline...

**Comment by sabakakado** [comment]
Tried to use asyncLocalStorage and localforage . 
for some reason, your package doesn't write to neither of them.

this is the offlineLink object
```
OfflineLink {storage: LocalForage, sequential: false, retryOnServerError: false, queue: Map(0), delayedSync: ƒ, …}
client: ApolloClient {defaultOptions: {…}, resetStoreCallbacks: Array(0), clearStoreCallbacks: Array(0), link: ApolloLink, cache: InMemoryCache, …}
delayedSync: ƒ debounced()
prefix: "offlineLink"
queue: Map(0) {}
retryOnServerError: false
sequential: false
storage: LocalForage {INDEXEDDB: "asyncStorage", WEBSQL: "webSQLStorage", LOCALSTORAGE: "localStorageWrapper", _defaultConfig: {…}, _config: {…}, …}
__proto__: ApolloLink 
```

**Comment by sabakakado** [comment]
@miguelocarvajal 
ok figure it out and almost there! 
with my mutations i send header with authorization key and i found out that it doesn't send with the queued mutation.. 
do you know a way to send it?

**Comment by miguelocarvajal** [comment]
Odd! Because the mutations are queued and sent with Apollo so it's actually Apollo's job to add the header to the request.

I am assuming you're using a link for this, make sure they are in the right order and the header should be added.
