### ISSUE TITLE
throwing an error on edge

### ISSUE THREAD

**Issue by Hasan-git** [carvajalconsultants/apollo-link-offline#3]
first of all thank you for the great effort !
every thing is fine on chrome, while it's throwing an error on edge

![image](https://user-images.githubusercontent.com/8820596/56717752-045baf80-6746-11e9-8143-a3e4c2813110.png)

pointing -> 
![image](https://user-images.githubusercontent.com/8820596/56717867-48e74b00-6746-11e9-93ec-ec6e48af587c.png)

**Comment by miguelocarvajal** [comment]
Thanks!

Glad to know it's working on Chrome, we've not used this from a browser yet. What is your use case (out of curiosity)?

This seems to be an issue with the package not being transpiled, check your Babel (if that's what you're using) settings to make sure that the client receives a supported version of JavaScript.

**Comment by Hasan-git** [comment]
Thanks for support !

A web app using angular 7. the app wasn't able to launch on edge and throwing this error.
Actually, I found that this error was thrown on development mode build while it's ok on production mode and this seems ok for me right now.

**Comment by miguelocarvajal** [comment]
Great to know it's working for you!

This definitely sounds, like an issue with your build setup since it works in production mode. I am not familiar with Angular so I cannot be of much help here though.

I am closing this ticket for now, should you need anything else feel free to open another.
