### ISSUE TITLE
update() callback from useMutation() is not fired if connection takes too long to resume

### ISSUE THREAD

**Issue by rgbedin** [carvajalconsultants/apollo-link-offline#8]
First of all, I'd like to say thank you for making such a great library publicly available. 

**Environment**:
- React Native (Non-Expo)
- Apollo Client v3.3.6 (`@apollo/client`)
- Running on iOS simulator 14.2 using Network Link Conditioner to simulate offline status
- Also happens on real device when turning airplane mode on/Wi-Fi off

**The issue I'm encountering happens if**:
1. App fires a mutation when the network is not available (i.e. 100% Loss profile on Network Link Conditioner)
2. Mutation returns with optimistic response (as expected) and tries to reach server (as expected)
2. Some arbitrary long amount of time elapses with network off (~15+ seconds)
3. The network connectivity resumes (i.e. Network Link Conditioner is turned off)
4. Mutation is fired again, is does resolve on the server. The app logs the return using a `operationLogLink` (as expected)
5. `update` callback of the `useMutation()` initially fired is not triggered (_note that this callback is triggered normally if there are not network errors or if the network resumes in a reasonable amount of time ~<10 seconds)_

I suspect it's something related to the `apollo-link-offline` because if I remove it from the links, the app hands back a network error on the `onError()` callback; triggered on the `useMutation()` hook. Moreover, the link works as expected if the network resumes in ~<10 seconds.

**For reference, this is how I am setting up my links and Apollo client**:
```javascript
// Setup links
const httpLink = createHttpLink({
  uri: ENV.GRAPHQL_SERVER_URI
});

const operationLogLink = new ApolloLink((operation, forward) => {
  console.info(
    `TauriaApolloContext: [${operation.operationName}] start:`,
    operation.variables
  );
  operation.setContext({ start: new Date() });

  return forward(operation).map((data) => {
    const duration =
      new Date().valueOf() - operation.getContext().start.valueOf();
    console.info(
      `TauriaApolloContext: [${operation.operationName}] [${duration}ms]:`,
      data
    );

    return data;
  });
});

const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      console.warn(
        `GraphQL error: Message: ${message}, Location: ${locations}, Path: ${path}`
      )
    );
  if (networkError) {
    // TODO: display network error UI
    console.warn(`GraphQL network error: ${networkError}`);
  }
});

const offlineLink = new OfflineLink({
  storage: AsyncStorage
});

const authLink = setContext((_, { headers }) => {
  return {
    headers: {
      ...headers,
      authorization: storedSessionRef.current?.accessToken
        ? `Bearer ${storedSessionRef.current?.accessToken}`
        : '',
      orgGuid: storedSessionRef.current?.orgGuid || ''
    }
  };
});

const link = from([
  authLink,
  operationLogLink,
  errorLink,
  offlineLink,
  httpLink
]);

// Setup cache and persistor
const cache = apolloCache;

const newPersistor = new CachePersistor({
  cache,
  storage: new AsyncStorageWrapper(AsyncStorage),
  debug: __DEV__,
  trigger: 'write'
});

await newPersistor.restore();
setPersistor(newPersistor);

// Check if we have initial cache
const cacheSize = await newPersistor.getSize();
setHasStoredCache(!!cacheSize && cacheSize > 0);

// Finally, create client
const client = new ApolloClient({
  link,
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network',
      nextFetchPolicy: 'cache-first',
            errorPolicy: 'all'
          },
          query: {
            errorPolicy: 'all'
          },
          mutate: {
            errorPolicy: 'all'
          }
        },
        cache,
        connectToDevTools: true
      });

      // Extra step required by apollo-link-offline
      await offlineLink.setup(client);

      setClient(client);
```

And this is the code that creates/fires the mutation:
```javascript
const [postMessage] = usePostMessageMutation({
  optimisticResponse: getOptimisticResponse(channelGuid, message),
  update(_, { data: newMessageData }) {
    console.info('Composer: update called', newMessageData);
    if (!newMessageData) {
      return;
    }

    const newMessage: NewMessage = newMessageData.postMessage;

    // if (isTemporaryGuid(newMessageData.postMessage.guid)) {
    //   setOptimisticMessage(newMessage);
    // } else {
    //   setOptimisticMessage(undefined);
    // }

    addNewMessageToCache(newMessage);
  },
  onError() {
    if (optimisticMessage) {
      const unsentMessage: NewMessage = {
        ...optimisticMessage,
        status: MessageStatus.Unsent
      };

      addNewMessageToCache(unsentMessage);
    }

    console.error('Composer: failed to send message');
  }
});
```
Just for clarity: you can see on the `update()` callback the very first thing it does is logging into the console. That action is not performed on the failed scenario described, but it does get called on all other circumstances.

**Comment by rgbedin** [comment]
From my investigation, it seems that if I remove this piece of code when creating the `ApolloClient` the issue is resolved:

```javascript
defaultOptions: {
  watchQuery: {
    fetchPolicy: 'cache-and-network',
    nextFetchPolicy: 'cache-first',
    errorPolicy: 'all'
  },
  query: {
    errorPolicy: 'all'
  },
  mutate: {
    errorPolicy: 'all'
  }
},
```

However the docs shows as example to set these default options. I am not sure if I am misunderstanding the use of the library or missing anything. Sorry.

**Comment by miguelocarvajal** [comment]
Hey @rgbedin!

Thanks for reaching out! I hope the library is of use to you.

We had similar issues with the scenario you are describing, it was made even worse when the network connection is off and the user closed the app and then opened it again when the network connection came back.

Upon further researching we found that the issue lay within Apollo itself as you can see in the issue here:

https://github.com/afafafafafaf/apollo-link-watched-mutation/issues/15

I had tried to find/resolve the issue myself with not much luck. I currently do not have the time to tackle the issue but hopefully there is enough data in the above issue that will help you get started.

If you do find a solution please let me know, I will take a look to see if I can help in any way.
